name: "[ANY BRANCH] lint codebase"

on:
  workflow_dispatch:

# push:
#   branches:
#     - kiwi
#     - master

jobs:
  build:
    name: Run source-code linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Running Super-Linter
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: kiwi
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: ./.github/linters/
          JAVA_FILE_NAME: google_checks.xml

