name: "CHROMIUM: update files from upstream"

on:
  workflow_dispatch:
    inputs:
      NEW_CHROMIUM_MAJOR:
        description: "Chromium major version:"
        required: true
        default: '93'

      NEW_CHROMIUM_MINOR:
        description: "Chromium minor version:"
        required: true
        default: '0'

      NEW_CHROMIUM_BUILD:
        description: "Chromium build version:"
        required: true
        default: '4577'

      NEW_CHROMIUM_PATCH:
        description: "Chromium patch version:"
        required: true
        default: '25'

  pull_request:

env:
  CHROMIUM_MAJOR:
  CHROMIUM_MINOR:
  CHROMIUM_BUILD:
  CHROMIUM_PATCH:
  verfile: CHROMIUM_VERSION
  filelist: /tmp/source_files.txt
  tmpdir: /tmp/chromium_new

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # for some reasons Git thinks it is a good idea to compact the Chromium repository
      - name: Disable Git auto-packing
        run: |
          git config --global gc.auto 0

      - name: Set up GitHub username
        run: |
          git config --global user.email "github@actions"
          git config --global user.name "Repository manager"

      - name: Disable Git pager
        run: |
          git config --global core.pager 'cat'

      - name: Prepare local Chromium branch
        run: |
          git switch chromium

      - name: Load settings from CHROMIUM_VERSION
        run: |
          if [ -r "${{ env.verfile }}" ]
          then
            source "${{ env.verfile }}"
            export $( cut -d= -f1 "${{ env.verfile }}" | grep -vF '#' )
            env | grep -F "CHROMIUM_" >> $GITHUB_ENV
          fi

      - name: List source files
        run: |
          {
            find . -type f | \
            sed 's!\./!/!g' | \
            grep -vFi '.gitignore'
          } > "${{ env.filelist }}"

      # https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/
      # git clone --filter=tree:0 <url> creates a treeless clone
      #
      # these clones download all reachable commits while fetching trees and blobs on-demand
      # these clones are best for build environments where the repository will be deleted after a single build, but you still need access to commit history
      - name: Check out Chromium
        run: |
          git clone --filter=tree:0 --no-checkout https://github.com/chromium/chromium.git "${{ env.tmpdir }}/"

      - name: Limit checkout file list
        run: |
          cd "${{ env.tmpdir }}/" && \
          git sparse-checkout set --stdin < "${{ env.filelist }}"

      - name: Switch Chromium to requested version
        run: |
          cd "${{ env.tmpdir }}/" && \
          git read-tree -mu ${{ github.event.inputs.NEW_CHROMIUM_MAJOR }}.${{ github.event.inputs.NEW_CHROMIUM_MINOR }}.${{ github.event.inputs.NEW_CHROMIUM_BUILD }}.${{ github.event.inputs.NEW_CHROMIUM_PATCH }}

      - name: Copy files to local Chromium branch
        run: |
          rsync -avz --progress --exclude=".git" "${{ env.tmpdir }}"/* .

      - name: Add files to local Chromium branch
        run: |
          git add .

      - name: Update CHROMIUM_VERSION file
        run: |
          {
            echo "CHROMIUM_MAJOR=${{ github.event.inputs.NEW_CHROMIUM_MAJOR }}"
            echo "CHROMIUM_MINOR=${{ github.event.inputs.NEW_CHROMIUM_MINOR }}"
            echo "CHROMIUM_BUILD=${{ github.event.inputs.NEW_CHROMIUM_BUILD }}"
            echo "CHROMIUM_PATCH=${{ github.event.inputs.NEW_CHROMIUM_PATCH }}"
          } > "${{ env.verfile }}"

      - name: Create pull request
        id: pullrequest
        uses: peter-evans/create-pull-request@v3
        with:
          branch: chromium_${{ github.event.inputs.NEW_CHROMIUM_MAJOR }}.${{ github.event.inputs.NEW_CHROMIUM_MINOR }}.${{ github.event.inputs.NEW_CHROMIUM_BUILD }}.${{ github.event.inputs.NEW_CHROMIUM_PATCH }}
          base: chromium
          delete-branch: true
          signoff: true
          title: "Update Chromium version ${{ env.CHROMIUM_MAJOR }}.${{ env.CHROMIUM_MINOR }}.${{ env.CHROMIUM_BUILD }}.${{ env.CHROMIUM_PATCH }} to ${{ github.event.inputs.NEW_CHROMIUM_MAJOR }}.${{ github.event.inputs.NEW_CHROMIUM_MINOR }}.${{ github.event.inputs.NEW_CHROMIUM_BUILD }}.${{ github.event.inputs.NEW_CHROMIUM_PATCH }}"
          commit-message: "[CHROMIUM] update version ${{ env.CHROMIUM_MAJOR }}.${{ env.CHROMIUM_MINOR }}.${{ env.CHROMIUM_BUILD }}.${{ env.CHROMIUM_PATCH }} to ${{ github.event.inputs.NEW_CHROMIUM_MAJOR }}.${{ github.event.inputs.NEW_CHROMIUM_MINOR }}.${{ github.event.inputs.NEW_CHROMIUM_BUILD }}.${{ github.event.inputs.NEW_CHROMIUM_PATCH }}"
          body: |
            Version update initiated by ${{ github.actor }}

      - name: Get pull request info
        run: |
          echo "Pull request number - ${{ steps.pullrequest.outputs.pull-request-number }}"
          echo "Pull request URL - ${{ steps.pullrequest.outputs.pull-request-url }}"

